name = "apostrophe-website"
type = "javascript"
compatibility_date = "2024-01-01"
pages_build_caching_enabled = true

[build]
command = "echo 'No build step'"
cwd = "/"

[env.production]
name = "apostrophe-website"
routes = [
  { pattern = "apostrophecommunications.com", zone_name = "apostrophecommunications.com" }
]

[[env.production.routes]]
pattern = "*"
zone_name = "apostrophecommunications.com"
